import type { MinaryTask } from '../types/idea';

export const MINARY_TEMPLATES: Record<string, MinaryTask> = {
  problem_length: {
    checkId: 'problem_length',
    dimension: 'problemClarity',
    title: '고객 인터뷰 질문지 3개 작성하기',
    body: '실제로 이 문제를 겪는 사람 3명에게 물어볼 질문을 작성하세요. "언제, 얼마나 자주, 어떤 상황에서"를 기준으로 구체화하세요.',
    estimatedMinutes: 30,
    impact: 8,
    effort: 2,
    severity: 'high',
  },
  problem_specific: {
    checkId: 'problem_specific',
    dimension: 'problemClarity',
    title: '문제 발생 빈도와 규모를 수치로 정리하기',
    body: '"이 문제는 주 N회 발생하며, 약 N명이 겪고 있다"처럼 빈도와 규모를 숫자로 표현해 문제의 심각성을 구체화하세요.',
    estimatedMinutes: 30,
    impact: 7,
    effort: 2,
    severity: 'medium',
  },
  target_clarity: {
    checkId: 'target_clarity',
    dimension: 'problemClarity',
    title: '타겟 고객 페르소나 1장 카드 작성하기',
    body: '직업, 나이대, 하루 일과, 이 문제를 겪는 상황을 포함한 1페이지 페르소나 카드를 작성하세요.',
    estimatedMinutes: 60,
    impact: 7,
    effort: 3,
    severity: 'high',
  },
  target_specific: {
    checkId: 'target_specific',
    dimension: 'problemClarity',
    title: '타겟 고객 구체화 (직업/연령/행동 패턴 포함)',
    body: '타겟 고객의 직업, 연령대, 이 문제와 관련된 행동 패턴을 한 문장에 포함시켜 재작성하세요.',
    estimatedMinutes: 30,
    impact: 6,
    effort: 2,
    severity: 'medium',
  },
  problem_urgency: {
    checkId: 'problem_urgency',
    dimension: 'problemClarity',
    title: '고객 불편 감정을 문제 설명에 반영하기',
    body: '고객이 이 문제를 겪을 때 어떤 감정(불편함, 시간 낭비, 답답함)을 느끼는지 설명에 포함하세요.',
    estimatedMinutes: 20,
    impact: 5,
    effort: 1,
    severity: 'low',
  },
  has_existing_solution: {
    checkId: 'has_existing_solution',
    dimension: 'marketDemand',
    title: '현재 고객이 사용하는 대안 서비스 3개 조사하기',
    body: '이 문제를 해결하기 위해 고객이 현재 쓰고 있는 방법이나 서비스 3개를 찾아 이름, 가격, 주요 기능을 정리하세요.',
    estimatedMinutes: 60,
    impact: 8,
    effort: 3,
    severity: 'high',
  },
  market_size_provided: {
    checkId: 'market_size_provided',
    dimension: 'marketDemand',
    title: '유사 서비스 MAU/사용자 수 조사하기',
    body: '유사한 서비스의 월간 사용자 수, 다운로드 수, 또는 매출 정보를 검색하여 시장 규모를 추정하세요.',
    estimatedMinutes: 90,
    impact: 8,
    effort: 4,
    severity: 'high',
  },
  market_size_quantified: {
    checkId: 'market_size_quantified',
    dimension: 'marketDemand',
    title: '시장 규모 계산식 작성하기 (TAM/SAM/SOM)',
    body: '"국내 타겟 고객 N만 명 × 평균 지불 의향 월 N원 = 연간 N억 원" 형태로 시장 규모 계산식을 작성하세요.',
    estimatedMinutes: 60,
    impact: 9,
    effort: 4,
    severity: 'high',
  },
  market_validation: {
    checkId: 'market_validation',
    dimension: 'marketDemand',
    title: '고객 반응 조사 (설문 5명 이상)',
    body: '타겟 고객 5명 이상에게 이 문제와 현재 해결 방법에 대한 짧은 설문을 진행하고 결과를 정리하세요.',
    estimatedMinutes: 120,
    impact: 9,
    effort: 5,
    severity: 'high',
  },
  diff_length: {
    checkId: 'diff_length',
    dimension: 'differentiation',
    title: '핵심 가치 제안 한 문장으로 정리하기',
    body: '"우리 서비스는 [타겟]이 [문제]를 겪을 때, [기존 대안]과 달리 [차별점]을 제공합니다" 형식으로 작성하세요.',
    estimatedMinutes: 30,
    impact: 7,
    effort: 2,
    severity: 'medium',
  },
  diff_specific: {
    checkId: 'diff_specific',
    dimension: 'differentiation',
    title: '경쟁 비교표 작성하기 (우리 vs 경쟁사 A vs B)',
    body: '우리 서비스와 주요 경쟁사 2개를 3~5개 기준(가격, 속도, 편의성 등)으로 비교하는 표를 작성하세요.',
    estimatedMinutes: 60,
    impact: 8,
    effort: 3,
    severity: 'high',
  },
  diff_unique: {
    checkId: 'diff_unique',
    dimension: 'differentiation',
    title: '우리만의 독자적 강점 1개 발굴하기',
    body: '"경쟁사가 따라오기 어려운 이유"를 기술, 팀, 데이터, 네트워크 관점에서 각각 1개씩 나열하고 가장 강한 것을 선택하세요.',
    estimatedMinutes: 45,
    impact: 7,
    effort: 3,
    severity: 'medium',
  },
  diff_measurable: {
    checkId: 'diff_measurable',
    dimension: 'differentiation',
    title: '차별점을 수치로 표현하기',
    body: '"N배 빠르다", "N% 저렴하다", "N시간 절약된다"처럼 차별점을 측정 가능한 수치로 바꾸세요.',
    estimatedMinutes: 30,
    impact: 8,
    effort: 2,
    severity: 'high',
  },
  channel_count: {
    checkId: 'channel_count',
    dimension: 'distributionStrategy',
    title: '첫 고객 확보 채널 1개 선정 + 실행 계획 작성',
    body: '가장 접근하기 쉬운 채널 1개를 선택하고 "이번 주에 N명에게 연락한다"는 구체적인 실행 계획을 작성하세요.',
    estimatedMinutes: 30,
    impact: 9,
    effort: 2,
    severity: 'high',
  },
  has_concrete_plan: {
    checkId: 'has_concrete_plan',
    dimension: 'distributionStrategy',
    title: '랜딩페이지 초안 작성하기 (헤드라인 + CTA)',
    body: '핵심 가치 제안을 담은 헤드라인 1개와 행동 유도 버튼(CTA) 문구를 작성하세요. 노션 또는 Carrd로 30분 안에 만들 수 있습니다.',
    estimatedMinutes: 60,
    impact: 8,
    effort: 3,
    severity: 'high',
  },
  plan_actionable: {
    checkId: 'plan_actionable',
    dimension: 'distributionStrategy',
    title: '첫 주 고객 확보 액션 3개 구체화하기',
    body: '이번 주 안에 실행할 수 있는 고객 확보 액션을 3개 작성하세요. 예: "커뮤니티 A에 소개글 게시", "지인 10명에게 DM 발송", "블로그 후기 작성 요청".',
    estimatedMinutes: 30,
    impact: 7,
    effort: 2,
    severity: 'medium',
  },
  stage_score: {
    checkId: 'stage_score',
    dimension: 'executionReadiness',
    title: '가설 검증 체크리스트 1개 완성하기',
    body: '"이 아이디어가 실제로 작동한다는 것을 어떤 증거로 확인할 수 있는가?"를 적고, 이번 주에 확인 가능한 가장 작은 실험 1개를 설계하세요.',
    estimatedMinutes: 45,
    impact: 8,
    effort: 3,
    severity: 'high',
  },
  time_score: {
    checkId: 'time_score',
    dimension: 'executionReadiness',
    title: '주간 작업 스케줄 블로킹하기',
    body: '이번 주 캘린더에 이 아이디어를 위한 시간 블록을 최소 3개 잡으세요. 각 블록에 구체적인 작업(인터뷰, 프로토타입 등)을 할당하세요.',
    estimatedMinutes: 20,
    impact: 6,
    effort: 1,
    severity: 'medium',
  },
  resource_count: {
    checkId: 'resource_count',
    dimension: 'executionReadiness',
    title: '보유 자원 인벤토리 작성 + 부족한 자원 파악',
    body: '현재 가진 자원(기술, 인맥, 자본, 경험)을 목록으로 작성하고, MVP를 만들기 위해 추가로 필요한 것 1~2개를 파악하세요.',
    estimatedMinutes: 30,
    impact: 5,
    effort: 2,
    severity: 'low',
  },
  stage_time_match: {
    checkId: 'stage_time_match',
    dimension: 'executionReadiness',
    title: '현재 단계에 맞는 마일스톤 3개 설정하기',
    body: '현재 단계(아이디어/검증/MVP)에서 다음 단계로 가기 위한 조건 3개를 구체적으로 작성하세요. 예: "인터뷰 10명 완료", "DAU 10명 달성".',
    estimatedMinutes: 30,
    impact: 7,
    effort: 2,
    severity: 'medium',
  },
  existing_solution_quality: {
    checkId: 'existing_solution_quality',
    dimension: 'marketDemand',
    title: '기존 대안의 불편함 포인트 3개 정리하기',
    body: '고객이 기존 대안에서 느끼는 가장 큰 불편함 3개를 구체적으로 작성하고, 우리가 어떻게 해결하는지 연결하세요.',
    estimatedMinutes: 45,
    impact: 8,
    effort: 2,
    severity: 'medium',
  },
};
